name: Auto-Approve Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  approve:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'nik13' && contains(github.event.pull_request.head.ref, 'hotfix')
    steps:
      - name: Auto Approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
